title: Szczepaniak-Bartek
url: "https://szczepaniak-bartek.github.io"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Home page and work portfolio of Szczepaniak Bartek

# Author details for the jekyll-seo-tag gem
author: 
  name: bartus
  email: szczepaniak.bartek@gmail.com
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
#social:
#  name: Urban Template
#  links:
#    - https://github.com/CloudCannon/urban-jekyll-template

collections:
  staff_members:
    output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

gems:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "clients"
    values:
      layout: "client"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
